FROM python:3.7.4-slim-buster

RUN sed -i 's/deb.debian.org/archive.debian.org/g; s/security.debian.org/archive.debian.org/g; /buster-updates/d' /etc/apt/sources.list \
    && apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -y --no-install-recommends \
    gcc libpq-dev && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir 'pip==19.2.3' 'setuptools==41.2.0' \
    'wheel==0.33.6' 'Flask==1.1.1' 'itsdangerous==1.1.0' \
    'Werkzeug==0.15.5' 'Jinja2==2.10.1' 'MarkupSafe==1.1.1' \
    'WTForms==2.2.1' 'Alembic==1.1.0' \
    'marshmallow==2.19.5' 'marshmallow-sqlalchemy==0.17.0' \
    'apache-airflow[postgres]==1.10.4'

ENV AIRFLOW_HOME=/opt/airflow
WORKDIR /opt/airflow
COPY setup.py requirements.txt ./
COPY src ./src
RUN pip install --no-cache-dir -e .
ENV PYTHONPATH=/opt/airflow/src
